[package]
name = "toyscript"
version = "0.1.0"
edition = "2021"

[lib]
name = "toyscript"
path = "src/lib.rs"

[dependencies]
peg = "0.8.0"
cranelift = "0.87.0"
cranelift-module = "0.87.0"
cranelift-jit = "0.87.0"
log = "0.4.17"
simplelog = "0.12.0"
